/*Given an integer n. You need to recreate the pattern given below for any value of N.
Let's say for N = 5, the pattern should look like as below:


*        *
**      **
***    ***
****  ****
**********
****  ****
***    ***
**      **
*        *

*/

public class Pattern_20 {
    public static void main(String[] args) {
        int n = 5;
        for(int i=n;i>=1;i--){
            for(int j=1;j<=n-i+1;j++){
                System.out.print("*");
            }
            
            for(int k=1; k<= 2*(i-1); k++){
            System.out.print(" ");
            }
            
            for(int j=1;j<=n-i+1;j++){
                System.out.print("*");
            }
            
            System.out.println("");
        }
        for(int i=1;i<=n-1;i++){
            for(int j=1;j<=n-i;j++){
                System.out.print("*");
            }
            
            for(int k=1; k<= 2*(i); k++){
            System.out.print(" ");
            }
            
            for(int j=1;j<=n-i;j++){
                System.out.print("*");
            }
            
            System.out.println("");
        }

    }
    
}

/*
 * PATTERN 20 - Hollow Diamond Star Pattern (Inverted)
 *
 * OUTPUT (n=5):
 * *        *
 * **      **
 * ***    ***
 * ****  ****
 * **********
 * ****  ****
 * ***    ***
 * **      **
 * *        *
 *
 * INTUITION:
 * - The pattern consists of two parts: the upper half (including the middle line) and the lower half.
 * - The upper half is generated by decreasing the number of stars and increasing the spaces, while the lower half does the opposite.
 *
 * WHY THIS WORKS:
 * - The first loop (i=n to 1) creates the upper half of the diamond, starting with n stars and decreasing to 1 star, while increasing spaces in between.
 * - The second loop (i=1 to n-1) creates the lower half of the diamond, starting with 1 star and increasing to n-1 stars, while decreasing spaces in between.
    * - The number of spaces is calculated as 2*(i-1) for the upper half and 2*i for the lower half to maintain the symmetry of the diamond.        
    * For n=5:
    * Upper half:
    * Row 1: 5 stars, 0 spaces, 5 stars → "*
    * Row 2: 4 stars, 2 spaces, 4 stars → "**      **"
    * Row 3: 3 stars, 4 spaces, 3 stars → "***    ***"
    * Row 4: 2 stars, 6 spaces, 2 stars → "****  ****"
    * Row 5: 1 star, 8 spaces, 1 star → "**********"
    * Lower half:
    * Row 6: 2 stars, 6 spaces, 2 stars → "****  ****"
    * Row 7: 3 stars, 4 spaces, 3 stars → "***    ***"
    * Row 8: 4 stars, 2 spaces, 4 stars → "**      **"
    * Row 9: 5 stars, 0 spaces, 5 stars → "*        *"
    * This results in the desired hollow diamond pattern, with the correct number of stars and spaces to create the visual effect of a diamond shape.       
    * The use of nested loops allows for efficient construction of the pattern, with the outer loop controlling the number of rows and the inner loops handling the star and space generation for each row. 
    * The pattern effectively demonstrates how to manipulate loops and spacing to create complex shapes using simple characters.    
    * TIME COMPLEXITY  : O(n^2)
    * SPACE COMPLEXITY : O(1)
    * Note: The pattern is symmetrical, so we can use the same logic for both halves
    * of the diamond, which simplifies the implementation and ensures consistency in the output.
    * - The use of nested loops allows for efficient construction of the pattern, with clear separation of concerns for each part of the pattern (stars and spaces).
    * - The pattern effectively demonstrates how to manipulate loops and conditional logic to create complex shapes using
    *   simple characters, making it a common exercise in programming to understand nested loops and pattern generation.
    * - The pattern is a classic example of how to use nested loops to create visually appealing designs, and it can be easily modified to create variations by changing the characters or the spacing logic.
    * Overall, this pattern serves as a good example of how to use loops and character manipulation to create visually appealing patterns in Java.
    * 
 */
